# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
from idlelib.colorizer import prog_group_name_to_tag

from initialise import answer, hint
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

2.1.3


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
array = np.array([1,2,3,4,5,6,7,8,9,10],dtype=np.int32)
print(array.nbytes)
#OR
print(array.size * array.itemsize)

40
40


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
print(np.info)

<function info at 0x0000024032E39E40>


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
array = np.array(range(10,50))
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
print(array[::-1])

[10  9  8  7  6  5  4  3  2  1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
array = np.array(range(9)).reshape(3,3)
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
array = np.array([1,2,0,0,4,0])
print(np.nonzero(array))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
array = np.array(np.random.randint(0,100,size=(3,3,3)),dtype=np.int32)
array

array([[[90, 73,  4],
        [21, 54, 77],
        [92, 59, 10]],

       [[15, 88, 71],
        [54, 49, 28],
        [13, 58, 77]],

       [[73, 50, 40],
        [37, 40, 74],
        [85, 65, 53]]], dtype=int32)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
array = np.array(np.random.randint(0,100,size=(10,10)),dtype=np.int32)
print(array.min(),array.max())

3 94


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
array = np.array(np.random.randint(0,100,size=(30)),dtype=np.int32)
print(array.mean())

42.43333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
array = np.ones((5,5))
array[1:-1,1:-1] = 0
print(array)
#This is a classic NumPy slicing trick: 1:-1 means “everything except the first and last row/column.”

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
#array = np.zeros((10,10))
#array[1:-1,1:-1] = np.random.randint(0,100)
#print(array)

array = np.ones((10,10))
array = np.pad(array,1,'constant',constant_values=0)
print(array)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
array = np.diag(1+np.arange(4),k=-1)
print(array)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
array = np.zeros((8,8),dtype=int)
array[1::2,::2] = 1
array[::2,1::2] = 1
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
print(np.unravel_index(99,(6,7,8)))

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
array = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(array)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
mean = x.mean()
std = x.std()
normalize = (x-mean)/std
print(normalize)

[-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
matrix_1 = np.array(np.random.randint(0,100,size=(5,3)),dtype=np.int32)
matrix_2 = np.array(np.random.randint(0,100,size=(3,2)),dtype=np.int32)
print(matrix_1.dot(matrix_2))
print(matrix_1 @ matrix_2)

[[10914 10719]
 [ 4643  5342]
 [ 7176  5210]
 [ 4794  7313]
 [12433 10612]]
[[10914 10719]
 [ 4643  5342]
 [ 7176  5210]
 [ 4794  7313]
 [12433 10612]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
answer(27)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
try:
    print(np.array(0) / np.array(0))
    print(array(0) // array(0))
    print(np.array([np.nan]).astype(int).astype(float))
except RuntimeError:
    print("Error: division by zero or modulo by zero")


nan
0
[-9.22337204e+18]


C:\Users\Arup sarkar\AppData\Local\Temp\ipykernel_8656\1304018433.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Arup sarkar\AppData\Local\Temp\ipykernel_8656\1304018433.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(array(0) // array(0))
C:\Users\Arup sarkar\AppData\Local\Temp\ipykernel_8656\1304018433.py:4: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [30]:
array_1 = np.array([1,2,3,4,5])
array_2 = np.array([3,4,5,6,7])
print(np.intersect1d(array_1,array_2))

[3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [31]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [32]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
#False

nan
1j


C:\Users\Arup sarkar\AppData\Local\Temp\ipykernel_8656\2596059867.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [33]:
yesterday = np.datetime64("today") - np.timedelta64(1, "D")
today = np.datetime64("today")
tomorrow = np.datetime64("today") + np.timedelta64(1, "D")
print(f'Yesterday: {yesterday}\nToday: {today}\nTomorrow: {tomorrow}')

Yesterday: 2026-04-03
Today: 2026-04-04
Tomorrow: 2026-04-05


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
np.arange(np.datetime64("2016-07-01"), np.datetime64("2016-08-01"), np.timedelta64(1, "D"))

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [36]:
z = np.random.uniform(0,10,10)
print(z.astype(int))
print(np.floor(z))
print(np.trunc(z))
print(np.around(z))

[8 4 7 5 8 8 8 3 5 1]
[8. 4. 7. 5. 8. 8. 8. 3. 5. 1.]
[8. 4. 7. 5. 8. 8. 8. 3. 5. 1.]
[9. 4. 8. 6. 9. 8. 8. 3. 6. 2.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [37]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)
#without broadcasting
z = np.tile(np.arange(5),(5,1))
print(z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [38]:
array = np.array(np.random.randint(0,10,size=(10),dtype=np.int32))
print(array)
array.sort()
print(array)

[2 2 5 9 1 2 8 8 9 7]
[1 2 2 2 5 7 8 8 9 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [39]:
array = np.arange(10)
np.add.reduce(array)


np.int64(45)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [43]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [49]:
Z = np.zeros(10)
Z.flags.writeable = False
#Z[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [50]:
array = np.array(np.random.randint(0,10,size=(10),dtype=np.int32))
print(array)
array[array == array.max()] = 0
print(array)

[1 6 5 8 4 6 7 6 2 1]
[1 6 5 0 4 6 7 6 2 1]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)